# general configuration
url: http://ryanlessing.com
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: #"/images/compass.png"
  # author will appear under the avatar (optional)
  author: "Ryan Lessing"
  # tagline will appear under the title (optional)
  tagline: #"I'm an undergraduate studying applied math and economics at<br> Brown University"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true  
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true

  meta_description: "Incoming J.D. Candidate at Yale Law School, Ex Associate at J.P. Morgan. Email: ryan.lessing@yale.edu · LinkedIn: linkedin.com/in/ryanlessing"

  description: "I'm an incoming J.D. candidate at Yale Law School, and was formerly an associate in Fixed Income Strategy at J.P. Morgan, focused on short-term fixed income markets. <br/></br> I graduated from Brown University with an Sc.B. in Applied Math-Economics."

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
